name: brep_mfr
channels:
  - pytorch
  - dglteam/label/cu117
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - six
  - dgl=1.0.0.cu117=py39_0
  - pip=23.2
  - gcc=9.5.0
  - gxx=9.5.0
  - pip:
      - pytorch-lightning==1.7.1
      - torchmetrics==0.10.3
      - torch-geometric==2.3.1
      - numpy==1.23.5
      - ./fairseq
